[2024-11-29T19:39:56.301+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-11-29T19:39:56.406+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-29T18:00:00+00:00 [queued]>
[2024-11-29T19:39:56.431+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-29T18:00:00+00:00 [queued]>
[2024-11-29T19:39:56.432+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 4
[2024-11-29T19:39:56.479+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): store_openweathermap_data> on 2024-11-29 18:00:00+00:00
[2024-11-29T19:39:56.514+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=4141) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-11-29T19:39:56.519+0000] {standard_task_runner.py:64} INFO - Started process 4151 to run task
[2024-11-29T19:39:56.515+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'store_openweathermap_data', 'scheduled__2024-11-29T18:00:00+00:00', '--job-id', '58', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmp33to8gbg']
[2024-11-29T19:39:56.523+0000] {standard_task_runner.py:91} INFO - Job 58: Subtask store_openweathermap_data
[2024-11-29T19:39:56.664+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.store_openweathermap_data scheduled__2024-11-29T18:00:00+00:00 [running]> on host 8885fe629c2f
[2024-11-29T19:39:56.931+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='store_openweathermap_data' AIRFLOW_CTX_EXECUTION_DATE='2024-11-29T18:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-11-29T18:00:00+00:00'
[2024-11-29T19:39:56.938+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-11-29T19:39:56.983+0000] {conn.py:362} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: connecting to broker:9092 [('172.23.0.9', 9092) IPv4]
[2024-11-29T19:39:56.985+0000] {conn.py:957} INFO - Probing node bootstrap-0 broker version
[2024-11-29T19:39:56.990+0000] {conn.py:393} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: Connection complete.
[2024-11-29T19:39:57.107+0000] {conn.py:1019} INFO - Broker version identified as 2.6.0
[2024-11-29T19:39:57.110+0000] {conn.py:1020} INFO - Set configuration api_version=(2, 6, 0) to skip auto check_version requests on startup
[2024-11-29T19:39:57.114+0000] {consumer.py:122} WARNING - group_id is None: disabling auto-commit.
[2024-11-29T19:39:57.115+0000] {subscription_state.py:167} INFO - Updating subscribed topics to: ('openweathermap_raw',)
[2024-11-29T19:39:57.121+0000] {subscription_state.py:253} INFO - Updated partition assignment: [('openweathermap_raw', 0)]
[2024-11-29T19:39:57.123+0000] {conn.py:362} INFO - <BrokerConnection node_id=1 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: connecting to broker:9092 [('172.23.0.9', 9092) IPv4]
[2024-11-29T19:39:57.125+0000] {conn.py:393} INFO - <BrokerConnection node_id=1 host=broker:9092 <connecting> [IPv4 ('172.23.0.9', 9092)]>: Connection complete.
[2024-11-29T19:39:57.126+0000] {conn.py:673} INFO - <BrokerConnection node_id=bootstrap-0 host=broker:9092 <connected> [IPv4 ('172.23.0.9', 9092)]>: Closing connection. 
[2024-11-29T19:39:57.363+0000] {logging_mixin.py:188} INFO - Consumed 100 records from topic openweathermap_raw
[2024-11-29T19:39:58.305+0000] {logging_mixin.py:188} INFO - Data from openweathermap_raw stored in /opt/***/data/parquet_files/openweathermap_data.parquet
[2024-11-29T19:39:58.316+0000] {python.py:237} INFO - Done. Returned value was: None
[2024-11-29T19:39:58.320+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-11-29T19:39:58.362+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=weather_data_kafka_dag, task_id=store_openweathermap_data, run_id=scheduled__2024-11-29T18:00:00+00:00, execution_date=20241129T180000, start_date=20241129T193956, end_date=20241129T193958
[2024-11-29T19:39:58.482+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 0
[2024-11-29T19:39:58.577+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-11-29T19:39:58.622+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
