[2024-12-03T13:32:20.006+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-12-03T13:32:20.055+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_kafka_dag.docker_cp_and_spark_submit manual__2024-12-03T13:26:45.759980+00:00 [queued]>
[2024-12-03T13:32:20.070+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_kafka_dag.docker_cp_and_spark_submit manual__2024-12-03T13:26:45.759980+00:00 [queued]>
[2024-12-03T13:32:20.071+0000] {taskinstance.py:2306} INFO - Starting attempt 2 of 4
[2024-12-03T13:32:20.087+0000] {taskinstance.py:2330} INFO - Executing <Task(BashOperator): docker_cp_and_spark_submit> on 2024-12-03 13:26:45.759980+00:00
[2024-12-03T13:32:20.094+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_kafka_dag', 'docker_cp_and_spark_submit', 'manual__2024-12-03T13:26:45.759980+00:00', '--job-id', '705', '--raw', '--subdir', 'DAGS_FOLDER/kafka_stream.py', '--cfg-path', '/tmp/tmpl_po394r']
[2024-12-03T13:32:20.096+0000] {standard_task_runner.py:91} INFO - Job 705: Subtask docker_cp_and_spark_submit
[2024-12-03T13:32:20.101+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:62 DeprecationWarning: This process (pid=1954) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2024-12-03T13:32:20.106+0000] {standard_task_runner.py:64} INFO - Started process 1956 to run task
[2024-12-03T13:32:20.183+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_kafka_dag.docker_cp_and_spark_submit manual__2024-12-03T13:26:45.759980+00:00 [running]> on host 0f9edd113eb4
[2024-12-03T13:32:20.321+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='admin' AIRFLOW_CTX_DAG_ID='weather_data_kafka_dag' AIRFLOW_CTX_TASK_ID='docker_cp_and_spark_submit' AIRFLOW_CTX_EXECUTION_DATE='2024-12-03T13:26:45.759980+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-12-03T13:26:45.759980+00:00'
[2024-12-03T13:32:20.323+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-12-03T13:32:20.338+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2024-12-03T13:32:20.339+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n            docker exec -it spark-master spark-submit --packages com.datastax.spark:spark-cassandra-connector_2.12:3.5.1  --py-files /dependencies.zip   /spark_stream.py\n        ']
[2024-12-03T13:32:20.347+0000] {subprocess.py:86} INFO - Output:
[2024-12-03T13:32:20.365+0000] {subprocess.py:93} INFO - the input device is not a TTY
[2024-12-03T13:32:20.366+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2024-12-03T13:32:20.367+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-12-03T13:32:20.373+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2024-12-03T13:32:20.376+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=weather_data_kafka_dag, task_id=docker_cp_and_spark_submit, run_id=manual__2024-12-03T13:26:45.759980+00:00, execution_date=20241203T132645, start_date=20241203T133220, end_date=20241203T133220
[2024-12-03T13:32:20.387+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 705 for task docker_cp_and_spark_submit (Bash command failed. The command returned a non-zero exit code 1.; 1956)
[2024-12-03T13:32:20.404+0000] {local_task_job_runner.py:243} INFO - Task exited with return code 1
[2024-12-03T13:32:20.416+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-12-03T13:32:20.419+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
